
server:
  port: 8081
  servlet:
    context-path: /auth
    session:
      cookie:
        name: RESOURCE_SESSIONID

spring:
  servlet:
    multipart:
      fileSizeThreshold: 0
      maxFileSize: 1024MB
      maxRequestSize: 1048MB
  freemarker:
    cache: false
    templateLoaderPath:
      - "classpath:/templates/"
      - "file:templates/"
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      hikari.max-lifetime: 30000
      hikari.idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.fran.microservice.cas.authserver.dao.mapper